language: node_js
node_js:
  - '0.10'
  - '0.12'
env:
  - BROWSER_NAME=chrome BROWSER_VERSION=latest
  - BROWSER_NAME=safari BROWSER_VERSION=latest
  - BROWSER_NAME=ie BROWSER_VERSION=6
  - BROWSER_NAME=ie BROWSER_VERSION=7
  - BROWSER_NAME=ie BROWSER_VERSION=8
  - BROWSER_NAME=ie BROWSER_VERSION=9
  - BROWSER_NAME=ie BROWSER_VERSION=10 BROWSER_PLATFORM="Windows 2012"
  - BROWSER_NAME=ie BROWSER_VERSION=latest BROWSER_PLATFORM="Windows 2012"
  - BROWSER_NAME=iphone BROWSER_VERSION=6.1
  - BROWSER_NAME=iphone BROWSER_VERSION=7.1
  - BROWSER_NAME=android BROWSER_VERSION=4.0
  - BROWSER_NAME=android BROWSER_VERSION=4.1
  - BROWSER_NAME=android BROWSER_VERSION=4.2
  - BROWSER_NAME=android BROWSER_VERSION=4.3
  - BROWSER_NAME=android BROWSER_VERSION=4.4
sudo: false
notifications:
  irc: irc.freenode.org#socket.io